schema_version: 1

context:
  version: 0.1.0

package:
  name: geometry_utils
  version: ${{ version }}

source:
  url: https://github.com/NOAA-ORR-ERD/geometry_utils/archive/v${{ version }}.tar.gz
  sha256: 3677fe5df9bc3c2f954f7b6865b84da9e5772d865def37199c9088afe4bd7703

build:
  number: 1
  skip: match(python, "<3.10")
  script: ${{ PYTHON }} -m pip install -vv --no-deps .

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - python
        - numpy
        - cython >=3
    - make
    - cmake
    - ninja
  host:
    - python
    - pip
    - cython >=3
    - numpy
    - scikit-build-core
    - cython-cmake
  run:
    - python
    - numpy

tests:
  - python:
      imports:
        - geometry_utils
  - requirements:
      run:
        - pytest
    script:
      - pytest --pyargs geometry_utils

about:
  license: CC0-1.0
  license_file: LICENSE
  summary: Utilities for basic computational geometry directly with numpy arrays.
  homepage: https://github.com/NOAA-ORR-ERD/geometry_utils

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
    - PythonCHB
